add original properties for easier logging
spatie/laravel-settings pull request #57
Opened 2021-03-30 19:09 UTC by ragingdave

This goes to add the original properties into the settings class to allow activity logging. This takes the simpler approach like eloquent takes with just having a copy of the original properties alongside the settings rather than an explicit database call to reload properties we could already have.

2021-03-31 12:24 UTC, rubenvanassche requested changes
Looking great! Two remarks + could you add a test to check if the originalValues are indeed sent with the event?

2021-03-31 12:24 UTC, rubenvanassche commented on src/Settings.php
> +    protected $originalSettingProperties;
Can you rename this to `originalValues`? And type it as `?Collection` with `null` as default?

2021-03-31 12:24 UTC, rubenvanassche commented on src/Events/SavingSettings.php
> +        $this->old = $old;
Can you rename this to `originalValues`?

2021-04-02 16:32 UTC, ragingdave commented
@rubenvanassche Don't want to be pushy, but any chance you might be able to review/merge the update?

2021-04-07 12:48 UTC, rubenvanassche commented
Hi @ragingdave, thanks for the Pr merged!

2021-04-07 12:48 UTC, merged